version: '3.7'  # all docker-compose version https://docs.docker.com/compose/compose-file/

services:
  postgres:
    image: ${IMAGE_NAME}  # postgres image with postgis ready
    ports:
      - ${EXPOSED_PORT}:5432
    container_name: ${CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

    volumes:
      - v_postgres:/var/lib/postgresql/data
    networks:
      - n_postgres

    restart: unless-stopped

networks:
  n_postgres:
    driver: bridge
    name: ${NETWORK_NAME}  # forced name and no auto-prepended

volumes:
  v_postgres:
    name: docker_volume__${STACK_ID}
    driver: local
